semester_1/models.py
from datetime import datetime
from hashlib import md5

from flask_login import UserMixin

from semester_1 import db


association_user_group_table = db.Table('user_group',
                                        db.Column('user_id', db.ForeignKey('users.id'), primary_key=True),
                                        db.Column('group_id', db.ForeignKey('groups.id'), primary_key=True)
                                        )


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.Integer, unique=True, autoincrement=True, nullable=False, primary_key=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now())

    email = db.Column(db.String(100), nullable=False, unique=True)
    password = db.Column(db.TEXT, nullable=False)
    username = db.Column(db.String(100), nullable=False, unique=True)

    picture = db.Column(db.LargeBinary, nullable=True)
    titles = db.Column(db.TEXT, nullable=True)

    groups = db.relationship("Group",
                             secondary=association_user_group_table,
                             back_populates="users"
                             )
    posts = db.relationship("Post", backref="user", lazy=True)
    created_groups = db.relationship("Group", backref="creator", lazy=True)
    created_threads = db.relationship("Thread", backref="creator", lazy=True)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, size)

    def __repr__(self):
        return "<User(id='%s', username='%s', email='%s')>" % (self.id, self.username, self.email)


class Post(db.Model):
    __tablename__ = "posts"

    id = db.Column(db.Integer, unique=True, autoincrement=True, nullable=False, primary_key=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now())
    creator_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    content = db.Column(db.TEXT, nullable=False)
    thread_id = db.Column(db.Integer, db.ForeignKey('threads.id'), nullable=False)

    def __repr__(self):
        return "<Post(id='%s', created_at='%s', created_by='%s', content='%s')>" %\
               (self.id, self.created_at, self.creator_id, self.content)


class Thread(db.Model):
    __tablename__ = "threads"

    id = db.Column(db.Integer, unique=True, autoincrement=True, nullable=False, primary_key=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now())
    creator_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    last_active = db.Column(db.DateTime, nullable=False, default=datetime.now())

    name = db.Column(db.String(100), nullable=False, unique=True)
    about = db.Column(db.TEXT, nullable=False)
    group_id = db.Column(db.Integer, db.ForeignKey('groups.id'), nullable=True)

    posts = db.relationship("Post", backref="thread", lazy=True)

    def __repr__(self):
        return "<Thread(id='%s', name='%s', about='%s')>" %\
               (self.id, self.name, self.about)


class Group(db.Model):
    __tablename__ = "groups"

    id = db.Column(db.Integer, unique=True, autoincrement=True, nullable=False, primary_key=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now())
    creator_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    last_active = db.Column(db.DateTime, nullable=False, default=datetime.now())

    name = db.Column(db.String(100), nullable=False, unique=True)
    about = db.Column(db.TEXT, nullable=False)
    open_group = db.Column(db.BOOLEAN, nullable=False, default=True)

    users = db.relationship("User",
                            secondary=association_user_group_table,
                            back_populates="groups"
                            )
    thread = db.relationship("Thread", backref="group", lazy=True, uselist=False)

    def __repr__(self):
        return "<Group(id='%s', name='%s', about='%s')>" %\
               (self.id, self.name, self.about)

semester_1/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from config import DB_USER, DB_PASSWORD, SECRET_KEY


app = Flask(__name__, template_folder='templates', static_folder='static')
app.config['SQLALCHEMY_DATABASE_URI'] = f'postgresql://{DB_USER}:{DB_PASSWORD}@localhost/semester_1'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
app.config['DEBUG'] = True
app.config['SECRET_KEY'] = SECRET_KEY

db = SQLAlchemy(app)
migrate = Migrate(app, db)


from .models import User, Post, Thread, Group


login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


from .auth import auth as auth_blueprint
from .views import views as views_blueprint
app.register_blueprint(auth_blueprint)
app.register_blueprint(views_blueprint)

semester_1/auth.py
from flask import (
    Blueprint, flash, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

from flask_login import login_user, logout_user, current_user
from sqlalchemy import exc
from semester_1 import db
from semester_1.models import User


auth = Blueprint('auth', __name__)


def login_decorator(func):
    def wrapper(*args, **kwargs):
        if current_user.is_authenticated:
            return redirect(url_for('views.index'))
        return func(*args, **kwargs)
    wrapper.__name__ = func.__name__
    return wrapper


@auth.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        email = request.form['email']
        username = request.form['username']
        password = request.form['password']
        error = None

        if not email or not (('@' in email) and ('.' in email)):
            error = 'Invalid email.'
        elif not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif len(password) < 8:
            error = 'Password is too short.'

        if error is None:
            try:
                user = User(email=email, password=generate_password_hash(password), username=username)
                db.session.add(user)
                db.session.commit()
            except exc.SQLAlchemyError:
                error = 'User is already registered.'
            else:
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template('register.html')


@auth.route('/login', methods=('GET', 'POST'))
@login_decorator
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        remember = request.form.get('remember') is not None
        error = None

        user = User.query.filter_by(username=username).first()
        if user is None:
            error = 'Incorrect data.'
        elif not check_password_hash(user.password, password):
            error = 'Incorrect data.'

        if error is None:
            if remember:
                login_user(user, remember=True)
            else:
                login_user(user, remember=False)
            return redirect(url_for('views.index'))

        flash(error)

    return render_template('login.html')


@auth.route('/logout')
def logout():
    session.clear()
    logout_user()
    return redirect(url_for('views.index'))

semester_1/views.py
from datetime import datetime

from flask import Blueprint, render_template, session, redirect, url_for, request, Response, flash
from flask_login import login_required, current_user
from sqlalchemy import exc
from werkzeug.security import check_password_hash, generate_password_hash

from semester_1 import User, Thread, Group, Post, db

views = Blueprint('views', __name__)


@views.route('/index', methods=['GET', 'POST'])
@views.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        search = request.form['search']
        reverse = request.form.get('reverse') is not None
        sort_by = request.form['sort_by']
        page = request.args.get('page', 1, type=int)

        threads = Thread.query.filter(Thread.group_id == None)

        if search is not None:
            threads = threads.filter(Thread.name.contains(search))

        if reverse:
            if sort_by == 'age':
                threads = threads.order_by(Thread.created_at.desc())
            elif sort_by == 'last_active':
                threads = threads.order_by(Thread.last_active.desc())
        else:
            if sort_by == 'age':
                threads = threads.order_by(Thread.created_at)
            elif sort_by == 'last_active':
                threads = threads.order_by(Thread.last_active)

        threads = threads.paginate(page, 10, False)

        next_url = url_for('views.index', page=threads.next_num) \
            if threads.has_next else None
        prev_url = url_for('views.index', page=threads.prev_num) \
            if threads.has_prev else None

        return render_template("index.html", threads=threads.items, next_url=next_url,
                               prev_url=prev_url)

    page = request.args.get('page', 1, type=int)
    threads = Thread.query.filter(Thread.group_id == None).paginate(page, 10, False)
    next_url = url_for('views.index', page=threads.next_num) \
        if threads.has_next else None
    prev_url = url_for('views.index', page=threads.prev_num) \
        if threads.has_prev else None
    return render_template("index.html", threads=threads.items, next_url=next_url, prev_url=prev_url)


@views.route('/groups', methods=['GET', 'POST'])
def groups():
    if request.method == 'POST':
        search = request.form['search']
        reverse = request.form.get('reverse') is not None
        sort_by = request.form['sort_by']
        page = request.args.get('page', 1, type=int)

        groups = Group.query

        if search is not None:
            groups = groups.filter(Group.name.contains(search))

        if reverse:
            if sort_by == 'age':
                groups = groups.order_by(Group.created_at.desc())
            elif sort_by == 'last_active':
                groups = groups.order_by(Group.last_active.desc())
        else:
            if sort_by == 'age':
                groups = groups.order_by(Group.created_at)
            elif sort_by == 'last_active':
                groups = groups.order_by(Group.last_active)

        groups = groups.paginate(page, 10, False)
        next_url = url_for('views.groups', page=groups.next_num) \
            if groups.has_next else None
        prev_url = url_for('views.groups', page=groups.prev_num) \
            if groups.has_prev else None
        return render_template("groups.html", groups=groups.items, next_url=next_url,
                               prev_url=prev_url)

    page = request.args.get('page', 1, type=int)
    groups = Group.query.paginate(page, 10, False)
    next_url = url_for('views.groups', page=groups.next_num) \
        if groups.has_next else None
    prev_url = url_for('views.groups', page=groups.prev_num) \
        if groups.has_prev else None
    return render_template("groups.html", groups=groups.items, next_url=next_url, prev_url=prev_url)


@views.route('/create_thread', methods=['GET', 'POST'])
@login_required
def create_thread():
    if request.method == 'POST':
        name = request.form['name']
        about = request.form['about']
        error = None

        if Thread.query.filter_by(name=name).first():
            error = "Thread with that name already exists."
        else:
            thread = Thread(name=name, about=about, creator_id=current_user.id)
            db.session.add(thread)
            db.session.commit()
            return redirect(url_for("views.index"))

        flash(error)

    return render_template('create_thread.html')


@views.route('/create_group', methods=['GET', 'POST'])
@login_required
def create_group():
    if request.method == 'POST':
        name = request.form['name']
        about = request.form['about']
        error = None

        if Thread.query.filter(Thread.group_id != None, Thread.name == name).first():
            error = "Group with that name already exists."
        else:
            user = User.query.filter_by(id=current_user.id).first()
            group = Group(name=name, about=about, creator_id=user.id)
            group.users.append(user)
            db.session.add(group)
            db.session.commit()
            thread = Thread(name=name, about=about, creator_id=user.id, group_id=group.id)
            db.session.add(thread)
            db.session.commit()
            return redirect(url_for("views.index"))

        flash(error)

    return render_template('create_group.html')


@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    if request.method == 'POST':
        email = request.form['email']
        username = request.form['username']
        password = request.form['password']
        titles = request.form['titles']
        error = None

        if not (('@' in email) and ('.' in email)) and email:
            error = 'Invalid email.'
        elif len(password) < 8 and password:
            error = 'Password is too short.'

        if error is None:
            try:
                user = User.query.filter_by(id=current_user.id).first()
                if email:
                    user.email = email
                if username:
                    user.username = username
                if password:
                    user.password = generate_password_hash(password)
                if titles:
                    user.titles = titles
                db.session.commit()
            except exc.SQLAlchemyError:
                error = 'User is already registered.'
            else:
                return redirect(url_for("views.index"))

        flash(error)

    return render_template('profile.html')


@views.route('/thread/<int:thread_id>', methods=['GET', 'POST'])
def thread(thread_id):
    if request.method == 'POST':
        if not current_user.is_authenticated:
            redirect(url_for('auth.login'))
        content = request.form["content"]
        if content:
            post = Post(creator_id=current_user.id, thread_id=thread_id, content=content)
            db.session.add(post)
            db.session.commit()
            thread = Thread.query.filter(Thread.id == post.thread_id).first()
            thread.last_active = datetime.now()
            db.session.commit()
            return redirect(url_for('views.thread', thread_id=thread_id))

    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter(Post.thread_id == thread_id).paginate(page, 10, False)
    replies = posts.total
    thread_obj = Thread.query.filter(Thread.id == thread_id).first()
    next_url = url_for('views.thread', thread_id=thread_id, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('views.thread', thread_id=thread_id, page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('thread.html', thread=thread_obj, replies=replies, posts=posts.items, next_url=next_url, prev_url=prev_url)


@views.route('/group/<int:group_id>', methods=['GET', 'POST'])
def group(group_id):
    if request.method == 'POST':
        if not current_user.is_authenticated:
            redirect(url_for('auth.login'))

        content = request.form["content"]
        group_obj = Group.query.filter(Group.id == group_id).first()
        if current_user not in group_obj.users:
            flash("To reply you should join the group first!")
        elif content:
            post = Post(creator_id=current_user.id, thread_id=group_obj.thread.id, content=content)
            db.session.add(post)
            db.session.commit()
            group_obj.last_active = datetime.now()
            thread = Thread.query.filter(Thread.id == post.thread_id).first()
            thread.last_active = datetime.now()
            db.session.commit()
            return redirect(url_for('views.group', group_id=group_id))

    page = request.args.get('page', 1, type=int)
    group_obj = Group.query.filter(Group.id == group_id).first()
    posts = Post.query.filter(Post.thread_id == group_obj.thread.id).paginate(page, 10, False)
    replies = posts.total
    next_url = url_for('group', group_id=group_id, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('group', group_id=group_id, page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('group.html', group=group_obj, replies=replies, posts=posts.items, next_url=next_url, prev_url=prev_url)


@views.route('/group_join/<int:group_id>', methods=['GET', 'POST'])
def group_join(group_id):
    group = Group.query.filter(Group.id == group_id).first()
    group.users.append(current_user)
    db.session.commit()
    return redirect(url_for('views.group', group_id=group_id))

semester_1/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Document{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

{% block header %}
<header>
    <div class="logo_container">
        <img src="{{ url_for('static', filename='logo.svg') }}" alt="LOGO" class="logo">
        CrushRoll
    </div>

    <div class="nav_container">
        <nav>
            <a href="{{ url_for('views.index') }}">Home</a>
            <a href="{{ url_for('views.groups') }}">Groups</a>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('views.profile') }}">Profile</a>
            {% else %}
            <a href="{{ url_for('auth.login') }}">Sign in</a>
            <a href="{{ url_for('auth.register') }}">Sign up</a>
            {% endif %}
        </nav>

        {% if current_user.is_authenticated %}
        <div class="profile_header_container">
            <img src="{{current_user.avatar(40)}}" alt="Ava">
            <div class="profile_header_text">
                <a href="{{ url_for('views.profile') }}" class="profile_header_name">{{current_user.username}}</a>
                <a href="{{ url_for('auth.logout') }}" class="profile_header_logout">Log out</a>
            </div>
        </div>
        {% endif %}
    </div>
</header>
{% endblock %}

{% block content %}
<main>

</main>
{% endblock %}

{% block footer %}
<footer>

</footer>
{% endblock %}

</body>
</html>

semester_1/templates/create_group.html
{% extends 'base.html' %}

{% block title %}Create_group{% endblock %}

{% block content %}
<main>
    <div class="form_wrapper">
        <form action="{{ url_for('views.create_group') }}" method="POST" class="login_form">
            <h3>Create group</h3>
            <input type="text" name="name" id="name" placeholder="Title">
            <input type="text" name="about" id="about" placeholder="About">
            <input type="submit" value="Create" id="login_submit">
        </form>
    </div>
</main>
{% endblock %}

semester_1/templates/create_thread.html
{% extends 'base.html' %}

{% block title %}Create_thread{% endblock %}

{% block content %}
<main>
    <div class="form_wrapper">
        <form action="{{ url_for('views.create_thread') }}" method="POST" class="login_form">
            <h3>Create thread</h3>
            <input type="text" name="name" id="name" placeholder="Title">
            <input type="text" name="about" id="about" placeholder="About">
            <input type="submit" value="Create" id="login_submit">
        </form>
    </div>
</main>
{% endblock %}

semester_1/templates/group.html
{% extends 'base.html' %}

{% block title %}Group{{group.id}}{% endblock %}

{% block content %}

<main>
    <div class="control_panel_group">
        <div class="top">
            <div class="group_info">
                <img src="{{group.creator.avatar(80)}}" alt="Ava" class="author_avatar">
                <div class="main_group_info">
                    <h3>{{group.name}}</h3>
                    <h5>Created by {{group.creator.username}} {{group.created_at.date().isoformat()}}</h5>
                    <div>
                        {% if group.open_group %}
                        <span>Open group</span>
                        {% endif %}
                        <span>{{group.users|length}} members</span>
                        <span>Last active: {{group.last_active.date().isoformat()}}</span>
                    </div>
                </div>
            </div>
            <div class="group_replies">
                {{replies}} replies
            </div>
        </div>

        <div class="separator white"></div>

        <div class="down">
            <h3>About this group:</h3>
            <p>{{group.about}}</p>
        </div>
    </div>

    {% for item in posts %}
        <div class="post">
            <div class="author">
                <img src="{{item.user.avatar(80)}}" alt="Ava" class="author_avatar">
                <h3>{{item.user.username}}</h3>
            </div>

            <div class="content">
                <p class="posted_time">Posted {{item.created_at.date().isoformat()}} at {{ item.created_at.time().strftime('%H:%M:%S') }}</p>
                <p class="post_content">{{item.content}}</p>
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        {% if prev_url %}
        <a href="{{ prev_url }}"> < </a>
        {% endif %}
        {% if next_url %}
        <a href="{{ next_url }}"> > </a>
        {% endif %}
    </div>

    {% if current_user.is_authenticated and current_user in group.users %}
    <form action="{{ url_for('views.group', group_id=group.id) }}" method="POST" class="send_post_form">
        <label for="content">Write your reply:</label>
        <textarea name="content" id="content"></textarea>
        <input type="submit" class="post_submit" value="Send">
    </form>
    {% else %}
    {% if current_user.is_authenticated and current_user not in group.users %}
    <form action="{{ url_for('views.group_join', group_id=group.id) }}" method="POST" class="send_post_form">
        <input type="number" name="group_id" id="group_id" value="{{group.id}}">
        <input type="submit" class="post_submit" value="Join">
    </form>
    {% endif %}
    {% endif %}
</main>
{% endblock %}

semester_1/templates/groups.html
{% extends 'base.html' %}

{% block title %}Groups{% endblock %}

{% block content %}
<main>
    <div class="control_panel">
        <form action="{{ url_for('views.groups') }}" method="POST" id="search_form">
            <div>
                <input type="text" placeholder="Search..." name="search" id="search" maxlength="100">
                <input type="submit" value="Search" id="submit">
            </div>

            <div>
                <label for="reverse">Reverse order:</label>
                <input type="checkbox" name="reverse" id="reverse" value="reverse">

                <label for="sort_by">Sort by:</label>
                <select name="sort_by" id="sort_by" form="search_form">
                    <option value="age">Age</option>
                    <option value="last_active">Last Active</option>
                </select>
            </div>
        </form>

        <a href="{{ url_for('views.create_group') }}" class="new_button">New group</a>
    </div>

    {% for item in groups %}
        <div class="group">
            <div class="group_header">
                <div class="left">
                    <img src="{{item.creator.avatar(40)}}" alt="Ava" class="author_avatar">
                    <div class="group_info">
                        <a href="{{ url_for('views.group', group_id=item.id) }}" class="header_link">{{item.name}}</a>
                        {% if item.open_group %}
                        <span>Open group</span>
                        {% endif %}
                        <span>{{item.users|length}} members</span>
                        <span>Last active: {{item.last_active.date().isoformat()}}</span>
                    </div>
                </div>
                <div class="right">
                    {{item.thread.posts|length}} replies
                </div>
            </div>

            <div class="separator"></div>

            <div class="group_about">
                {{item.about}}
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        {% if prev_url %}
        <a href="{{ prev_url }}"> < </a>
        {% endif %}
        {% if next_url %}
        <a href="{{ next_url }}"> > </a>
        {% endif %}
    </div>
</main>
{% endblock %}

semester_1/templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block content %}
<main>
    <div class="control_panel">
        <form action="{{ url_for('views.index') }}" method="POST" id="search_form">
            <div>
                <input type="text" placeholder="Search..." name="search" id="search" maxlength="100">
                <input type="submit" value="Search" id="submit">
            </div>

            <div>
                <label for="reverse">Reverse order:</label>
                <input type="checkbox" name="reverse" id="reverse" value="reverse">

                <label for="sort_by">Sort by:</label>
                <select name="sort_by" id="sort_by" form="search_form">
                    <option value="age">Age</option>
                    <option value="last_active">Last Active</option>
                </select>
            </div>
        </form>

        <a href="{{ url_for('views.create_thread') }}" class="new_button">New thread</a>
    </div>

    {% for item in threads %}
        <div class="thread">
            <div>
                <a href="{{ url_for('views.thread', thread_id=item.id) }}" class="header_link">{{item.name}}</a>
                <h5 class="last_active">Last active: {{item.last_active.date().isoformat()}}</h5>
            </div>

            <div>
                <img src="{{item.creator.avatar(30)}}" alt="Ava" class="author_avatar">
                <h3>{{item.creator.username}}</h3>
                <h5>{{item.created_at.date().isoformat()}}</h5>
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        {% if prev_url %}
        <a href="{{ prev_url }}"> < </a>
        {% endif %}
        {% if next_url %}
        <a href="{{ next_url }}"> > </a>
        {% endif %}
    </div>
</main>
{% endblock %}

semester_1/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<main>
    <div class="form_wrapper">
        <form action="{{ url_for('auth.login') }}" method="POST" class="login_form">
            <h3>Sign in</h3>
            <input type="text" name="username" id="username" placeholder="Username">
            <input type="password" name="password" id="password" placeholder="Password">
            <div class="remember_me">
                <input type="checkbox" name="remember" id="remember">
                Remember me
            </div>
            <input type="submit" value="Sign in" id="login_submit">
        </form>
        <div class="login_signup">
            <p>Don't have an account?</p>
            <a href="{{ url_for('auth.register') }}" class="login_link">Sign up</a>
        </div>
    </div>
</main>
{% endblock %}

semester_1/templates/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<main>
    <div class="form_wrapper">
        <form action="{{ url_for('views.profile') }}" method="POST" class="login_form">
            <h3>Edit profile</h3>
            <input type="email" name="email" id="email" placeholder="Email">
            <input type="text" name="username" id="username" placeholder="Username">
            <input type="password" name="password" id="password" placeholder="Password">
            <input type="text" name="titles" id="titles" placeholder="Favorite titles">
            <input type="submit" value="Save" id="login_submit">
        </form>
    </div>
</main>
{% endblock %}

semester_1/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<main>
    <div class="form_wrapper">
        <form action="{{ url_for('auth.register') }}" method="POST" class="login_form">
            <h3>Sign up</h3>
            <input type="email" name="email" id="email" placeholder="Email">
            <input type="text" name="username" id="username" placeholder="Username">
            <input type="password" name="password" id="password" placeholder="Password">

            <input type="submit" value="Sign up" id="login_submit">
        </form>
        <div class="login_signup">
            <p>Already have an account?</p>
            <a href="{{ url_for('auth.login') }}" class="login_link">Sign in</a>
        </div>
    </div>
</main>
{% endblock %}

semester_1/templates/thread.html
{% extends 'base.html' %}

{% block title %}Thread{{thread.id}}{% endblock %}

{% block content %}
<main>
    <div class="control_panel_thread">
        <div class="left">
            <h3>{{thread.name}}</h3>
            <p>Created by {{thread.creator.username}} {{thread.created_at.date().isoformat()}}</p>
        </div>
        <div class="right">
            {{replies}} replies
        </div>
    </div>

    {% for item in posts %}
        <div class="post">
            <div class="author">
                <img src="{{item.user.avatar(80)}}" alt="Ava" class="author_avatar">
                <h3>{{item.user.username}}</h3>
            </div>

            <div class="content">
                <p class="posted_time">Posted {{item.created_at.date().isoformat()}} at {{ item.created_at.time().strftime('%H:%M:%S') }}</p>
                <p class="post_content">{{item.content}}</p>
            </div>
        </div>
    {% endfor %}

    <div class="pagination">
        {% if prev_url %}
        <a href="{{ prev_url }}"> < </a>
        {% endif %}
        {% if next_url %}
        <a href="{{ next_url }}"> > </a>
        {% endif %}
    </div>

    {% if current_user.is_authenticated %}
    <form action="{{ url_for('views.thread', thread_id=thread.id) }}" method="POST" class="send_post_form">
        <label for="content">Write your reply:</label>
        <textarea name="content" id="content"></textarea>
        <input type="submit" class="post_submit" value="Send">
    </form>
    {% endif %}
</main>
{% endblock %}